version: 2.1

orbs:
  buildevents: honeycombio/buildevents

jobs:
  setup:
    steps:
      - setup_linux

  myjob:
    steps:
      - with_job_span:
          steps:
            - run: be-cmd first -- echo "real work here"
            - run: be-cmd sleepytime -- sleep 10
            - run: be-cmd penultimate -- echo "do some more things"
            # - berun:
            #     name: last
            #     command: echo "publish"

  cleanup:
    steps:
      - finish_trace

workflows:
  build:
    jobs:
      - setup
      - myjob:
          requires:
          - setup
      - cleanup:
          requires:
          - cleanup
