version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.14.0

workflows:
  # build runs on checkins
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          checkout: true
          orb-name: honeycombio/buildevents
          orb-path: orb.yml
          publish-alpha-version: false
          publish-sha-version: false
          branch-sha-version-ref: dev:${CIRCLE_BRANCH}
          publish-branch-sha-version: true
          requires:
            - orb-tools/lint
  promote:
    jobs:
      - orb-tools/publish:
          orb-path: orb.yml
          orb-ref: honeycombio/buildevents@${CIRCLE_TAG}
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
